### ISSUE TITLE
POST with json in the body does not work.

### ISSUE THREAD

**Issue by tosho-ait** [villadora/express-http-proxy#114]
When trying to proxy POST requests with json data in the body the server receives an empty body.

I managed to work around it with:
`
app.use('/api..., proxy(be, {
    decorateRequest: function(reqOpt, req) {
        reqOpt.bodyContent = JSON.stringify(reqOpt.bodyContent)
        return reqOpt;
    }
}));
`
It seems that bodyContent is an object instead of a string ...

**Comment by monkpow** [comment]
@tosho-ait I think this issue is resolved by the latest commit to master (b8e2c60064effcfa7551191042ee619ccdcc5837) , but I am looking for outside verification before i publish this version to npm.   Do you mind trying the master branch and letting me know if it closes your issue?

If it does not, would you please give me a little more information about your use case?

Thanks!

**Comment by monkpow** [comment]
Published "Better handling for request body when body is JSON."  Feel free to reopen if you'd like to continue the discussion.
