### ISSUE TITLE
Dynamic host

### ISSUE THREAD

**Issue by adanba** [villadora/express-http-proxy#128]
Hi, 

I can't  make my host dynamic, i use this code snippet:  

```
var proxy = require('express-http-proxy');
var app = require('express')();
app.use('/proxy', 
      function(req,res) {
          return proxy(req.session.dynamic_host);
      }
).listen(8080);
console.log("listening on port 8080")
```

The host is in the session params.

With this code, it try to download the page until the timeout appears, it seems to be a blocking some where but i have any idea how to solve it.

Please can someone help there ?

**Comment by monkpow** [comment]
I think you want
```
var proxy = require('express-http-proxy');
var app = require('express')();
app.use('/proxy',  function (req) { 
  return req.session.dynamic_host; 
}).listen(8080);
console.log("listening on port 8080")
```

**Comment by monkpow** [comment]
I added a test to show this a16ff7242006c07ad43f55d8958c71d0109f9a4b.   Hope this helps.

**Comment by adanba** [comment]
@monkpow Thank you very much

**Comment by oxmane** [comment]
@monkpow this actually doesn't allow for a different host for each request, if I'm not mistaken.

Due to this line https://github.com/villadora/express-http-proxy/blob/master/index.js#L38 if I understand correctly the `parsedHost` variable will be initialized on the first request and then won't change even if `parseHost` would return a different host for subsequent requests.

**Comment by oxmane** [comment]
@monkpow I've actually open a pull request with a test which demonstrates the issue and a fix which should solve it.
https://github.com/villadora/express-http-proxy/pull/134
