### ISSUE TITLE
Instead of proxying it redirects

### ISSUE THREAD

**Issue by ht512512** [villadora/express-http-proxy#255]
I was having trouble using the module with my sailsjs app so I tested it with the following simple express test server and it instead of proxying, redirected browser to the target (www.google.com for the test).

Server code
---------------
```
const express = require('express');
const app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
})

var proxy = require('express-http-proxy');
app.use('/proxy', proxy('www.google.com'));

app.listen(1337, function () {
  console.log('Example app listening on port 1337!');
})
```
Browser to http://192.168.1.211:1337/proxy returned 302 redirect to 
   Location:https//www.google.com/?gws_rd=ssl

I have attached the navigation trace as an image.
![proxy-redirect](https://user-images.githubusercontent.com/3441504/28242277-204ab400-695c-11e7-9b71-e4cbf87083a4.png)
Shouldn't it proxy the traffic through! Is this a configuration issue?

**Comment by monkpow** [comment]
Hi @ht512512,

Thanks for the question.     

The way I'm reading it, it looks like the proxy does pass through to your requested proxy address 'http://google.com' and that request to google returns a 302 to ```/?gws_rd=ssl```.

IOW, You are seeing a request from the browser to ```/proxy``` returns 302, because the proxied call (on server side) to ```http://google.com``` returns a 302.

There is a DEBUG option that can you help you trace the request path in express-http-proxy.   See the README if this sounds like it might be helpful to you.

**Comment by jazoom** [comment]
I had the same confusion. Possibly don't use google.com as the example?
