### ISSUE TITLE
Intercept fallthrough

### ISSUE THREAD

**Issue by mfowlewebs** [villadora/express-http-proxy#39]
Presently, there are two options if using intercept: return/send the content, or throw an error. The third option that is not available is to continue the middleware chain normally, taking no action.

I dont think I ought to [have to compose Error-middleware](https://github.com/mfowlewebs/http-proxy/blob/master/server.js#L47) to handle failure cases of http-proxy; intercept should let me simply call next() to continue the processing chain. 

If I do try to call a naked `next()`, say- [on this line](https://github.com/mfowlewebs/http-proxy/blob/master/server.js#L41)- I get `TypeError: Cannot read property 'length' of undefined`. This should instead continue the middleware chain normally instead, I feel.

**Comment by monkpow** [comment]
@mfowlewebs In the example you've provided, the issue is that you are clobbering the ```next``` middleware argument with a local argument, here:

```
		intercept: function(rsp, data, req, res, next){
```
The argument in this position is for the callback to continue processing after intercept, so when you do

```
   next("Content Not Found")
```
 
You are actually calling intercept's callback,  replacing the original response data, with "Content Not Found", and providing ```undefined``` as the second argument (e.g. your post-intercepted response).


I think your case is likely to work if you instead name your inbound argument 'cb' or 'callback' or 'interceptContinuation', so that you still have access to the express specific ```next``` method.

```js
intercept: function(rsp, data, req, res, anythingButNext){
	if(rsp.statusCode >= 200 && rsp.statusCode < 400){
				anythingButNext(null, data)
			}else{
				next("Content not found")
			}
		}
```


Let me know how it works out for you.
