### ISSUE TITLE
Unable to access locals in proxy functions

### ISSUE THREAD

**Issue by grapevineai** [villadora/express-http-proxy#456]
I am using the `res.locals` to pass variables from a middleware (https://expressjs.com/en/api.html#res.locals) but some proxy functions (such as `proxyReqOptDecorator` and `proxyReqPathResolver` ) don't give access to the `res` parameter.

What is the recommended way to pass variables from a middleware to a proxy?

**Comment by monkpow** [comment]
Hi @grapevineai,
Sorry for the long delay in responding. Let me know if you are still interested in this topic and I'd be happy to chat about this.

**Comment by monkpow** [comment]
Without more details, I'd propose this is due to an intention design decision; to avoid cross talk between steps and between the host application and the module to the greatest degree possible. In other words, each workflow step intentionally only exposes the fields the 'step' expects to operate on.

`proxyReqOptDecorator` and `proxyReqPathResolver` both accept user defined functions, so you can set vars directly in your functions, or you can use partially applied functions to enclose local variables.

Hope this is helpful. I'd be happy to re-open the discussion if you're interested, or if you feel I misunderstand your concern.
