### ISSUE TITLE
Override redirect location set by proxied host

### ISSUE THREAD

**Issue by reecefenwick** [villadora/express-http-proxy#52]
I'm currently using this library to intercept and inject some headers for my angular app, the proxy server is listening on port 3000 and forwarding to the host on port 8080

There are some scenarios where the proxied host responds with a redirect to a URL like:
- http://localhost:8080/#/thing/thingIdentifier

Note that the port is not quite what I need - I need it to be 3000.

As far I can tell, from looking at the source; this is not currently possible.

**Questions:**
1. Am I correct?
2. Has this requirement been raised before?
3. Does this seem like something reasonable to be implemented?

Let me know if I can provide more information.

**Comment by monkpow** [comment]
This capability currently exists, using the intercept feature.   I am adding a test to demonstrate how it could be used.

This could also be solved in some app setups simply by using a relative path (```/#/thingIdentifier```) rather than a fully qualified URL (```http://localhost:8080/#/thing/thingIdentifier```).

IOW, if you're on 'www.server.com:3000' and get a redirect of ```/#/thingidentifier```, you'll be redirected to 
```www.server.com:3000//#/thingidentifier```, without needing to intercept the response.

**Comment by monkpow** [comment]
See commit ```043ee94e11e19a32c486209a3dc6e492ab209f2a```

**Comment by monkpow** [comment]
Closing issue as answered question.
