### ISSUE TITLE
when I post json data to  proxy, it alway return "Empty reply from server"?

### ISSUE THREAD

**Issue by likesxuqiang** [villadora/express-http-proxy#7]
But when I post same data to the third server, it return ok. how can I do?
1, post to the third server .
curl -X "POST" http://localhost:9000/v2/images  -d '{"image": {}}'
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 9000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9000 (#0)
> POST /v2/images HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:9000
> Content-type: application/json
> Accept:application/json
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
< Date: Fri, 26 Sep 2014 14:52:05 GMT
< Server: WSGIServer/0.1 Python/2.7.6
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
<
* Closing connection 0

2, post to proxy.  it waits for a timeout. 
curl -X "POST" http://localhost:3000/proxy/v2/images  -d '{"image": {}}' -H "Content-type: application/json" -H "Accept:application/json" -v
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /proxy/v2/images HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:3000
> Content-type: application/json
> Accept:application/json
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server

**Comment by mingzepeng** [comment]
@likesxuqiang  thanks a lot,your reply helps me to solve my problem

**Comment by brianpchsu** [comment]
I faced the same issue earlier and this definitely help. However, I couldn't understand why we need to put proxy before the bodyParser? I thought it should be reverse?!!!

**Comment by jasonadt** [comment]
+1 for @likesxuqiang 's answer, it fixed my issue as well.

**Comment by bitdivine** [comment]
Hello, I too would be interested to know the answer to @brianpchsu 's question.  Many thanks.

**Comment by bitdivine** [comment]
Alas I don't have the option of putting this proxy before body-parser.  I might have to roll my own.

**Comment by oliverwoodings** [comment]
@brianpchsu @bitdivine the reason you need the proxy before `body-parser` is because the body of the request is a readable stream. The stream is a one-time thing - once it is read, it is then 'empty'. If you have `body-parser` before the proxy, this is what happens:

1. Request comes in
1. `body-parser` reads all the content out of the raw body stream and puts it on `req.body`
1. `express-http-proxy` then tries to read the stream, however it has already been read so it is empty
1. Request is proxied with an empty body

You might be wondering why `express-http-proxy` can't use `req.body`. This is because it has no idea what to do with the content on `req.body` - it would effectively have to 'undo' whatever `body-parser` did before. What could be done instead is adding a method to the proxy options called `getBody` that could allow you to override how the body content is retrieved. Might put in a PR for this, think it would be useful!

One option you could try for now is not mounting the body-parser middleware on your entire app. E.g.:

```js
var app = express()
app.use('/api', bodyParser.json())
app.use('/proxy', proxy('foo.com', {})
```

**Comment by monkpow** [comment]
This feels resolved by previous authors to me.  Feel free to reopen if you'd like to continue the conversation.
